version: "3"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    configs:
      - source: schema
        target: /docker-entrypoint-initdb.d/schema.sql
    command: ["postgres", "-c", "log_statement=all"]

configs:
  schema:
    file: sql/schema.sql
