// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: groups.sql

package schema

import (
	"context"
)

const createGroup = `-- name: CreateGroup :exec
INSERT INTO groups (name, location) VALUES ($1, $2)
`

type CreateGroupParams struct {
	Name     string
	Location int16
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) error {
	_, err := q.db.Exec(ctx, createGroup, arg.Name, arg.Location)
	return err
}
