// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: items.sql

package schema

import (
	"context"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (
  name, description
) VALUES (
  $1, $2
)
RETURNING id, name, description
`

type CreateItemParams struct {
	Name        string
	Description *string
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem, arg.Name, arg.Description)
	var i Item
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const createItemHasAuthorRelationship = `-- name: CreateItemHasAuthorRelationship :one
INSERT INTO item_has_author (
  item_id, author_id
) VALUES (
  $1, $2
)
RETURNING item_id, author_id
`

type CreateItemHasAuthorRelationshipParams struct {
	ItemID   int64
	AuthorID int64
}

func (q *Queries) CreateItemHasAuthorRelationship(ctx context.Context, arg CreateItemHasAuthorRelationshipParams) (ItemHasAuthor, error) {
	row := q.db.QueryRow(ctx, createItemHasAuthorRelationship, arg.ItemID, arg.AuthorID)
	var i ItemHasAuthor
	err := row.Scan(&i.ItemID, &i.AuthorID)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items
WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteItem, id)
	return err
}

const selectItem = `-- name: SelectItem :one
SELECT id, name, description FROM items
WHERE id = $1
`

func (q *Queries) SelectItem(ctx context.Context, id int64) (Item, error) {
	row := q.db.QueryRow(ctx, selectItem, id)
	var i Item
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const selectItems = `-- name: SelectItems :many
SELECT id, name, description FROM items
ORDER BY name
`

func (q *Queries) SelectItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.Query(ctx, selectItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectItemsWithAuthors = `-- name: SelectItemsWithAuthors :many

SELECT items.id, items.name, items.description,
CAST(
  CASE
    WHEN (array_length(array_remove(array_agg(authors.id), null), 1) > 0)
    THEN jsonb_agg((authors.id, authors.name))::jsonb
  END
AS jsonb) as authors
FROM items
left join item_has_author on items.id = item_has_author.item_id
left join authors on item_has_author.author_id = authors.id
group by items.id
`

type SelectItemsWithAuthorsRow struct {
	ID          int64
	Name        string
	Description *string
	Authors     []byte
}

// https://github.com/sqlc-dev/sqlc/issues/3238
func (q *Queries) SelectItemsWithAuthors(ctx context.Context) ([]SelectItemsWithAuthorsRow, error) {
	rows, err := q.db.Query(ctx, selectItemsWithAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectItemsWithAuthorsRow
	for rows.Next() {
		var i SelectItemsWithAuthorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Authors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectSingleItemWithAuthors = `-- name: SelectSingleItemWithAuthors :one
SELECT items.id, items.name, items.description,
CAST(
  CASE
    WHEN (array_length(array_remove(array_agg(authors.id), null), 1) > 0)
    THEN jsonb_agg((authors.id, authors.name))::jsonb
  END
AS jsonb) as authors
FROM items
left join item_has_author on items.id = item_has_author.item_id
left join authors on item_has_author.author_id = authors.id
where items.id = $1
group by items.id
`

type SelectSingleItemWithAuthorsRow struct {
	ID          int64
	Name        string
	Description *string
	Authors     []byte
}

func (q *Queries) SelectSingleItemWithAuthors(ctx context.Context, id int64) (SelectSingleItemWithAuthorsRow, error) {
	row := q.db.QueryRow(ctx, selectSingleItemWithAuthors, id)
	var i SelectSingleItemWithAuthorsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Authors,
	)
	return i, err
}
